/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.weather.views;

import com.sun.awt.AWTUtilities;
import com.weather.pojo.Configuration;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Frame;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collection;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Wong
 */
public class WeatherMain extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form WeatherMain
     */
    private int posX, posY;
    private DlgCityList dlg;
    private ExecutorService executorDlg = Executors.newFixedThreadPool(3);
    //private ExecutorService executorCalls = Executors.newFixedThreadPool(2);
    private Collection<Callable<String>> callables = new ArrayList<>();

    public WeatherMain() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        setAppIcon();
        setCursor();
        this.requestFocus();
    }

    public JButton getBtnAnterior() {
        return btnAnterior;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    private void setAppIcon() {
        URL url = getClass().getResource("/com/weather/images/icono.png");
        ImageIcon icon = new ImageIcon(url);
        this.setIconImage(icon.getImage());
    }

    private void setCursor() {
        Cursor cursor;
        ImageIcon image = new ImageIcon(getClass().getResource("/com/weather/images/cursorAmarillo.png"));
        Toolkit t = Toolkit.getDefaultToolkit();
        cursor = t.createCustomCursor(image.getImage(), new Point(1, 1), "Cursor");
        this.setCursor(cursor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlCentro = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlSplit_Izq = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddUbication = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        pnlSplit_der = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tbpane = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        pnlNorte = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenWeather");
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        pnlCentro.setBackground(new java.awt.Color(71, 71, 73));
        pnlCentro.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(250, 553));

        pnlSplit_Izq.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(71, 71, 73));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(71, 71, 73));
        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 167;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 6, 0, 6);
        jPanel2.add(jLabel1, gridBagConstraints);

        btnAddUbication.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        btnAddUbication.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUbication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/agregarUbicacion48.png"))); // NOI18N
        btnAddUbication.setText("Add Ubication");
        btnAddUbication.setContentAreaFilled(false);
        btnAddUbication.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddUbication.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/agregarUbicacion48.png"))); // NOI18N
        btnAddUbication.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/agregarUbicacion64.png"))); // NOI18N
        btnAddUbication.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddUbication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUbicationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 6, 0, 6);
        jPanel2.add(btnAddUbication, gridBagConstraints);

        jButton7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/cerrarTodo48.png"))); // NOI18N
        jButton7.setText("Close All Tabbs");
        jButton7.setContentAreaFilled(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/cerrarTodo48.png"))); // NOI18N
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/cerrarTodo64.png"))); // NOI18N
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 6, 88, 6);
        jPanel2.add(jButton7, gridBagConstraints);

        jButton8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/historial48.png"))); // NOI18N
        jButton8.setText("History");
        jButton8.setContentAreaFilled(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/historial48.png"))); // NOI18N
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/historial64.png"))); // NOI18N
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 6, 0, 6);
        jPanel2.add(jButton8, gridBagConstraints);

        pnlSplit_Izq.add(jPanel2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(pnlSplit_Izq);

        pnlSplit_der.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(71, 71, 73));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(tbpane, java.awt.BorderLayout.CENTER);

        pnlSplit_der.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(71, 71, 73));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/izquierda48.png"))); // NOI18N
        btnAnterior.setContentAreaFilled(false);
        btnAnterior.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/izquierda48.png"))); // NOI18N
        btnAnterior.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/izquierda64.png"))); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 318, 17, 0);
        jPanel4.add(btnAnterior, gridBagConstraints);

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/derecha48.png"))); // NOI18N
        btnSiguiente.setContentAreaFilled(false);
        btnSiguiente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/derecha48.png"))); // NOI18N
        btnSiguiente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/derecha64.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 37, 17, 298);
        jPanel4.add(btnSiguiente, gridBagConstraints);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/cerrarPestaña48.png"))); // NOI18N
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/cerrarPestaña48.png"))); // NOI18N
        btnEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/cerrarPestaña64.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 38, 17, 0);
        jPanel4.add(btnEliminar, gridBagConstraints);

        pnlSplit_der.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(pnlSplit_der);

        pnlCentro.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlNorte.setBackground(new java.awt.Color(233, 109, 73));
        pnlNorte.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlNorteMouseDragged(evt);
            }
        });
        pnlNorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlNorteMousePressed(evt);
            }
        });
        pnlNorte.setLayout(new java.awt.GridBagLayout());

        lblTexto.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/Ubicacion_48.png"))); // NOI18N
        lblTexto.setText("OpenWeather");
        lblTexto.setIconTextGap(-360);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 6, 305);
        pnlNorte.add(lblTexto, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/btnCerrar_48.png"))); // NOI18N
        jButton1.setToolTipText("Exit");
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/btnCerrar_48.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/btnCerrar_64.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 7);
        pnlNorte.add(jButton1, gridBagConstraints);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/Minimizar48.png"))); // NOI18N
        jButton2.setToolTipText("Minimize");
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/Minimizar48.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/Minimizar64.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 324, 6, 0);
        pnlNorte.add(jButton2, gridBagConstraints);

        getContentPane().add(pnlNorte, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(1180, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAddUbicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUbicationActionPerformed
        executorDlg.execute(this);
    }//GEN-LAST:event_btnAddUbicationActionPerformed

    private String addTabPane(String message) {
        for (int i = 0; i < Configuration.cityList.size(); i++) {
            tbpane.addTab(Configuration.cityList.get(i), new PnlWeather(Configuration.cityList.get(i)));
        }
        callables.addAll(callables);
        return message;
    }

    class AddTabbedPane implements Callable<String> {

        @Override
        public String call() throws Exception {
            Configuration.cityList.stream().forEach((city) -> {
                tbpane.addTab(city, new PnlWeather(city));
            });
            btnAnterior.setEnabled(true);
            btnEliminar.setEnabled(true);
            btnSiguiente.setEnabled(true);
            return "Completado";
        }

    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (!Configuration.cityList.isEmpty()) {
            int option = JOptionPane.showConfirmDialog(this, "Do you want to close all windows?", "Warning",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                tbpane.removeAll();
                Configuration.cityList.removeAll(Configuration.cityList);
                btnAnterior.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnSiguiente.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Successful!", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if (Configuration.cityList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No quedan mas pantallas", "Warning", JOptionPane.ERROR_MESSAGE);
        } else if (tbpane.getSelectedComponent() == null) {
            JOptionPane.showMessageDialog(this, "No quedan mas pantallas", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void pnlNorteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNorteMousePressed
        // TODO add your handling code here:
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_pnlNorteMousePressed

    private void pnlNorteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNorteMouseDragged
        // TODO add your handling code here:
        int newposX = evt.getXOnScreen() - posX;
        int newposY = evt.getYOnScreen() - posY;
        this.setLocation(newposX, newposY);
    }//GEN-LAST:event_pnlNorteMouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (Configuration.cityList.isEmpty()) {
            btnAnterior.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnSiguiente.setEnabled(false);
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Component c = tbpane.getSelectedComponent();
        if (c != null) {
            Configuration.cityList.remove(c.toString());
            tbpane.remove(c);
        } else {
            return;
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        int index = tbpane.getSelectedIndex();
        if ((index + 1) < tbpane.getTabCount()) {
            tbpane.setSelectedIndex(index + 1);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        int index = tbpane.getSelectedIndex();
        if ((index - 1) < 0) {
            return;
        }
        if ((index - 1) >= 0) {
            tbpane.setSelectedIndex(index - 1);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        executorDlg.shutdownNow();
        System.out.println(executorDlg);
    }//GEN-LAST:event_formWindowClosed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        /*int value = evt.getKeyCode();
        if (value == KeyEvent.VK_LEFT) {
            int index = tbpane.getSelectedIndex();
            if ((index - 1) < 0) {
                return;
            }
            if ((index - 1) >= 0) {
                tbpane.setSelectedIndex(index - 1);
            }
        } else if (value == KeyEvent.VK_RIGHT) {
            int index = tbpane.getSelectedIndex();
            if ((index + 1) < tbpane.getTabCount()) {
                tbpane.setSelectedIndex(index + 1);
            }
        }*/
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WeatherMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUbication;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSplit_Izq;
    private javax.swing.JPanel pnlSplit_der;
    private javax.swing.JTabbedPane tbpane;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        dlg = new DlgCityList(this, true);
        dlg.setVisible(true);
        if (dlg.isbtnSelected()) {
            executorDlg.submit(new AddTabbedPane());
        } else {
            return;
        }
    }

}
