/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.weather.views;

import com.weather.controller.PnlWeatherController;
import java.net.MalformedURLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.aksingh.owmjapis.api.APIException;
import net.aksingh.owmjapis.model.CurrentWeather;

/**
 *
 * @author Yasser
 */
public class PnlWeather extends javax.swing.JPanel {
    private PnlWeatherController pwc;

    private CurrentWeather weather;
    /**
     * Creates new form PnlWeather
     * @param cityName
     */
    public PnlWeather(String cityName) {
        
        pwc = new PnlWeatherController();
        try {
            weather = pwc.getWeather(cityName);
        } catch (APIException ex) {
            Logger.getLogger(PnlWeather.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblCity = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSunrise = new javax.swing.JLabel();
        lblSunset = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblHumidity = new javax.swing.JLabel();
        lblPressure = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblWind = new javax.swing.JLabel();
        lblFeel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblCity.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCity.setText("Ticuantepe");
        lblCity.setText(weather.getCityName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(lblCity, gridBagConstraints);

        lblTemperature.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lblTemperature.setForeground(new java.awt.Color(255, 255, 255));
        lblTemperature.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTemperature.setText("33°C");
        double temp = weather.getMainData().getTemp() - 273;
        lblTemperature.setText(String.valueOf((int)temp) + "°C");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(lblTemperature, gridBagConstraints);

        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescription.setText("Mostly Clear");
        lblDescription.setText(weather.getWeatherList().get(0).getDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(lblDescription, gridBagConstraints);

        try{
            lblImage.setIcon(pwc.getImageUrl(weather.getWeatherList().get(0).getIconCode()));
        }catch(MalformedURLException ex){
            Logger.getLogger(PnlWeather.class.getName()).log(Level.SEVERE,ex.getMessage());
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(lblImage, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 5, 0));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SUNRISE");
        jPanel2.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SUNSET");
        jPanel2.add(jLabel4);

        lblSunrise.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblSunrise.setForeground(new java.awt.Color(255, 255, 255));
        lblSunrise.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSunrise.setText("05:20");
        SimpleDateFormat format = new SimpleDateFormat("HH:mm");
        lblSunrise.setText(format.format(weather.getSystemData().getSunriseDateTime()).toString());
        jPanel2.add(lblSunrise);

        lblSunset.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblSunset.setForeground(new java.awt.Color(255, 255, 255));
        lblSunset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSunset.setText("18:10");
        lblSunset.setText(format.format(weather.getSystemData().getSunsetDateTime()).toString());
        jPanel2.add(lblSunset);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("HUMIDITY");
        jPanel2.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PRESSURE");
        jPanel2.add(jLabel8);

        lblHumidity.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblHumidity.setForeground(new java.awt.Color(255, 255, 255));
        lblHumidity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHumidity.setText("76%");
        lblHumidity.setText(weather.getMainData().getHumidity().toString() + "%");
        jPanel2.add(lblHumidity);

        lblPressure.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblPressure.setForeground(new java.awt.Color(255, 255, 255));
        lblPressure.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPressure.setText("1009 hPa");
        lblPressure.setText(weather.getMainData().getPressure().toString() + "hPa");
        jPanel2.add(lblPressure);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("WIND");
        jPanel2.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("FEELS LIKE");
        jPanel2.add(jLabel13);

        lblWind.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblWind.setForeground(new java.awt.Color(255, 255, 255));
        lblWind.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWind.setText("ENE 14 km/h");
        lblWind.setText(weather.getWindData().getDegree().toString() + ", "
            + weather.getWindData().getSpeed().toString() + "km/h");
        jPanel2.add(lblWind);

        lblFeel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblFeel.setForeground(new java.awt.Color(255, 255, 255));
        lblFeel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFeel.setText("32°");
        lblFeel.setText(String.valueOf((int)(weather.getMainData().getTempMax()  - 273)) + "°");
        jPanel2.add(lblFeel);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

//    @Override
//    public void paintComponent(Graphics g) {
//        super.paintComponent(g);
//        g.drawImage(new ImageIcon(getClass().getResource("/ni/edu/uni/fcys/yass/weather/img/weather.jpg")).getImage(), 0, 0, null);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblFeel;
    private javax.swing.JLabel lblHumidity;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPressure;
    private javax.swing.JLabel lblSunrise;
    private javax.swing.JLabel lblSunset;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblWind;
    // End of variables declaration//GEN-END:variables
}
