/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.weather.views;

import com.sun.awt.AWTUtilities;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import java.net.URL;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Wong
 */
public class WeatherLogo extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form WeatherLogo
     */
    private int i = 0;
    private int posX,posY;
    private ExecutorService executor;
    private boolean isRunning = false;
    
    public WeatherLogo() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        setAppIcon();
        setCursor();
        executor = Executors.newSingleThreadExecutor();
    }

    private void setAppIcon(){
        URL url = getClass().getResource("/com/weather/images/icono.png");
        ImageIcon icon = new ImageIcon(url);
        this.setIconImage(icon.getImage());
    }
    
    private void setCursor(){
        Cursor cursor;
        ImageIcon image = new ImageIcon(getClass().getResource("/com/weather/images/cursorAmarillo.png"));
        Toolkit t = Toolkit.getDefaultToolkit();
        cursor = t.createCustomCursor(image.getImage(), new Point(1,1), "Cursor");
        this.setCursor(cursor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSur = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        pgbCarga = new rojerusan.componentes.RSProgressCircle();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlSur.setBackground(new java.awt.Color(71, 71, 73));
        pnlSur.setLayout(new java.awt.GridBagLayout());

        lblTexto.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto.setText("L o a d i n g . . .");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 18, 7, 66);
        pnlSur.add(lblTexto, gridBagConstraints);

        pgbCarga.setForeground(new java.awt.Color(233, 109, 73));
        pgbCarga.setValue(0);
        pgbCarga.setColorText(new java.awt.Color(255, 255, 255));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.ipady = -67;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 15, 8, 0);
        pnlSur.add(pgbCarga, gridBagConstraints);

        getContentPane().add(pnlSur, java.awt.BorderLayout.SOUTH);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/weather/images/OpenWeather-Logo.jpg"))); // NOI18N
        lblImage.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblImageMouseDragged(evt);
            }
        });
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblImageMousePressed(evt);
            }
        });
        getContentPane().add(lblImage, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(599, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMousePressed
        // TODO add your handling code here:
        posX = evt.getX();
        posY = evt.getY();
    }//GEN-LAST:event_lblImageMousePressed

    private void lblImageMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseDragged
        // TODO add your handling code here:
        int newposX = evt.getXOnScreen() - posX;
        int newposY = evt.getYOnScreen() - posY;
        this.setLocation(newposX,newposY);
    }//GEN-LAST:event_lblImageMouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        isRunning = true;
        executor.execute(this);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if(executor.isShutdown()){
            new WeatherMain().setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherLogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WeatherLogo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTexto;
    private rojerusan.componentes.RSProgressCircle pgbCarga;
    private javax.swing.JPanel pnlSur;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(isRunning){
            pgbCarga.setValue(i++);
            try {
                Thread.sleep(45);
            } catch (InterruptedException ex) {
                Logger.getLogger(WeatherLogo.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(pgbCarga.getValue() == 100){
                this.dispose();
                isRunning = false;
                executor.shutdownNow();
            }
        }
    }
}
